services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports: ["8080:8080"]
    environment:
      ASPNETCORE_ENVIRONMENT: Staging
      ConnectionStrings__Postgres: Host=db; User ID=postgres; Password=postgres; Database=cafe_task
      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
      
  db:
    image: postgres:17.4
    ports: [ "5432:5432" ]
    environment: [ "POSTGRES_PASSWORD=postgres", "POSTGRES_USER=postgres" ]
    volumes: [ "./.docker-volumes/postgres:/var/lib/postgresql/data" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 15s
      timeout: 12s
      retries: 5
      start_period: 15s
      
  seq:
    image: datalust/seq:2024.3
    ports: [ "5341:80" ]
    environment: [ "ACCEPT_EULA=Y" ]
    volumes: [ "./.docker-volumes/seq:/data" ]

